#if DEBUG
import NeodexKit
import SwiftData
import SwiftUI

// Support for Xcode Previews. Everything here is compiled out of release builds, and the
// fixture it loads lives in `App/Preview Content`, which Xcode strips from archives.

extension PokedexDatabase {
    /// The curated fixture generated by `swift run neodex-data --preview-fixture`.
    /// Falls back to an empty database when the fixture isn't bundled.
    nonisolated static let preview: PokedexDatabase = {
        (try? PokedexDatabase.loadSynchronously(from: .main, subdirectory: nil, filePrefix: "preview-")) ?? .empty
    }()

    /// A Pokémon from the preview fixture by name, or a stand-in so previews never crash.
    func previewPokemon(_ name: String) -> Pokemon {
        pokemon(named: name) ?? pokemon.first ?? PokedexDatabase.placeholderPokemon
    }

    nonisolated static let placeholderPokemon = Pokemon(
        id: "missingno", name: "MissingNo.", displayName: "MissingNo.", nationalDexNumber: 0, generation: 1,
        types: [.normal], abilities: AbilitySet(primary: "noability"), baseStats: StatBlock(repeating: 50),
        height: 1, weight: 10, maleRatio: nil, imageID: "missingno"
    )
}

/// Hosts a pushed screen in a navigation stack with the preview database and an in-memory store.
struct PreviewHost<Content: View>: View {
    @ViewBuilder var content: Content

    var body: some View {
        NavigationStack { content.appDestinations() }
            .previewEnvironment()
    }
}

extension View {
    /// Injects the preview database, an app model and an in-memory SwiftData container.
    func previewEnvironment() -> some View {
        environment(\.database, .preview)
            .environment(AppModel())
            .modelContainer(PreviewStore.container)
    }
}

/// An in-memory SwiftData store seeded with a sample team and some browsing history.
@MainActor
enum PreviewStore {
    static let container: ModelContainer = {
        let configuration = ModelConfiguration(isStoredInMemoryOnly: true)
        let container = try! ModelContainer(for: SavedTeam.self, BrowsingRecord.self, configurations: configuration)
        let database = PokedexDatabase.preview
        let context = container.mainContext

        let members = ["Great Tusk", "Gholdengo", "Kingambit", "Ogerpon-Wellspring", "Dragonite", "Garchomp"]
            .compactMap { database.pokemon(named: $0) }
            .map { pokemon -> TeamMember in
                var member = TeamMember(pokemon: pokemon)
                member.itemID = database.item(id: "leftovers")?.id
                let moves = database.learnset(for: pokemon).prefix(4).map { Optional($0.move.id) }
                member.moveIDs = Array(moves) + Array(repeating: nil, count: 4 - moves.count)
                member.evs = StatBlock(hp: 4, attack: 252, speed: 252)
                return member
            }
        context.insert(SavedTeam(name: "Preview Team", format: "gen9ou", members: members))

        for name in ["Charizard", "Garchomp", "Pikachu", "Eevee", "Gengar"] {
            if let pokemon = database.pokemon(named: name) {
                context.insert(BrowsingRecord(kind: .pokemon, entityID: pokemon.id))
            }
        }
        if let move = database.move(named: "Earthquake") {
            context.insert(BrowsingRecord(kind: .move, entityID: move.id))
        }
        return container
    }()

    /// The seeded team.
    static var sampleTeam: SavedTeam {
        (try? container.mainContext.fetch(FetchDescriptor<SavedTeam>()))?.first ?? SavedTeam(name: "Preview Team")
    }
}
#endif
