//
//  Pokemon.swift
//  Neodex
//
//  Created by Ethan Marshall on 11/25/20.
//

import Foundation

struct Pokemon: Identifiable, Codable {
    
    // Variables
    let id = UUID()
    
    var name: String
    var nationalDexNum: String // The National Pokédex number
    var type1: String
    var type2: String // A blank string denotes no second type
    var speciesName: String
    var height: Double // In meters
    var weight: Double // In kilograms
    
    var ability1: String
    var ability2: String // A blank string denotes no second ability
    var hiddenAbility: String
    
    var EVYield: String
    var catchRate: Int
    var baseFriendship: Int
    var baseEXP: Int
    var growthRate: String
    var eggGroups: [String]
    var maleRate: Double // A percentage - a negative value means the pokemon is genderless
    var eggCycles: Int
    
    var baseStats: [Int] // Each element is one of the 6 stats. In order: HP, Atk, Def, SpAtk, SpDef, Speed
    
    var evolutions: [Evolution] // Lists the Pokémon's evolutions by their level, Pokémon evolving into, and method - see the Evolution struct.
    var dexEntries: [DexEntry]
    var locations: [String]
    
    // Enumerations
    enum CodingKeys: String, CodingKey {
        case id
        case name
        case nationalDexNum
        case type1
        case type2
        case speciesName
        case height
        case weight
        case ability1
        case ability2
        case ability3
        case hiddenAbility
        case EVYield
        case catchRate
        case baseFriendship
        case baseEXP
        case growthRate
        case eggGroups
        case maleRate
        case eggCycles
        case baseStats
        case evolutions
        case dexEntries
        case locations
    }
    
    static let firstForty: [Pokemon] = [
    
        Pokemon(name: "Bulbasaur", nationalDexNum: "001", type1: "Grass", type2: "Poison", speciesName: "Seed", height: 0.7, weight: 6.9, ability1: "Overgrow", ability2: "", hiddenAbility: "Chlorophyll", EVYield: "1 Sp. Atk", catchRate: 45, baseFriendship: 70, baseEXP: 64, growthRate: "Medium Slow", eggGroups: ["Grass", "Monster"], maleRate: 87.5, eggCycles: 20, baseStats: [45, 49, 49, 65, 65, 45], evolutions: [Evolution(level: 1, pokemon: "Bulbasaur", method: "", treeLevel: 1), Evolution(level: 16, pokemon: "Ivysaur", method: "Level Up", treeLevel: 2), Evolution(level: 32, pokemon: "Venusaur", method: "Level Up", treeLevel: 3)], dexEntries: [DexEntry(source: "Pokémon Sword", entry: "There is a plant seed on its back right from the day this Pokémon is born. The seed slowly grows larger."), DexEntry(source: "Pokémon Shield", entry: "While it is young, it uses the nutrients that are stored in the seed on its back in order to grow.")], locations: ["Master Dojo (gift)"]),
        
        Pokemon(name: "Ivysaur", nationalDexNum: "002", type1: "Grass", type2: "Poison", speciesName: "Seed", height: 1.0, weight: 13.0, ability1: "Overgrow", ability2: "", hiddenAbility: "Chlorophyll", EVYield: "1 Sp. Atk, 1 Sp. Def", catchRate: 45, baseFriendship: 70, baseEXP: 142, growthRate: "Medium Slow", eggGroups: ["Grass", "Monster"], maleRate: 87.5, eggCycles: 20, baseStats: [60, 62, 63, 80, 80, 60], evolutions: [Evolution(level: 1, pokemon: "Bulbasaur", method: "", treeLevel: 1), Evolution(level: 16, pokemon: "Ivysaur", method: "Level Up", treeLevel: 2), Evolution(level: 32, pokemon: "Venusaur", method: "Level Up", treeLevel: 3)], dexEntries: [DexEntry(source: "Pokémon Sword", entry: "When the bulb on its back grows large, it appears to lose the ability to stand on its hind legs."), DexEntry(source: "Pokémon Shield", entry: "Exposure to sunlight adds to its strength. Sunlight also makes the bud on its back grow larger.")], locations: []),
        
        Pokemon(name: "Venusaur", nationalDexNum: "003", type1: "Grass", type2: "Poison", speciesName: "Seed", height: 2.0, weight: 100.0, ability1: "Overgrow", ability2: "", hiddenAbility: "Chlorophyll", EVYield: "2 Sp. Atk, 1 Sp. Def", catchRate: 45, baseFriendship: 70, baseEXP: 236, growthRate: "Medium Slow", eggGroups: ["Grass", "Monster"], maleRate: 87.5, eggCycles: 20, baseStats: [80, 82, 83, 100, 100, 80], evolutions: [Evolution(level: 1, pokemon: "Bulbasaur", method: "", treeLevel: 1), Evolution(level: 16, pokemon: "Ivysaur", method: "Level Up", treeLevel: 2), Evolution(level: 32, pokemon: "Venusaur", method: "Level Up", treeLevel: 3)], dexEntries: [DexEntry(source: "Pokémon Sword", entry: "Its plant blooms when it is absorbing solar energy. It stays on the move to seek sunlight."), DexEntry(source: "Pokémon Shield", entry: "A bewitching aroma wafts from its flower. The fragrance becalms those engaged in a battle.")], locations: []),
        
        Pokemon(name: "Venusaur-Mega", nationalDexNum: "003", type1: "Grass", type2: "Poison", speciesName: "Seed", height: 2.4, weight: 155.5, ability1: "Thick Fat", ability2: "", hiddenAbility: "", EVYield: "2 Sp. Atk, 1 Sp. Def", catchRate: 45, baseFriendship: 70, baseEXP: 281, growthRate: "Medium Slow", eggGroups: ["Grass", "Monster"], maleRate: 87.5, eggCycles: 20, baseStats: [80, 100, 123, 122, 120, 80], evolutions: [Evolution(level: 1, pokemon: "Bulbasaur", method: "", treeLevel: 1), Evolution(level: 16, pokemon: "Ivysaur", method: "Level Up", treeLevel: 2), Evolution(level: 32, pokemon: "Venusaur", method: "Level Up", treeLevel: 3)], dexEntries: [DexEntry(source: "Pokémon Let's Go", entry: "In order to support its flower, which has grown larger due to Mega Evolution, its back and legs have become stronger."), DexEntry(source: "Pokémon Sword", entry: "Its plant blooms when it is absorbing solar energy. It stays on the move to seek sunlight."), DexEntry(source: "Pokémon Shield", entry: "A bewitching aroma wafts from its flower. The fragrance becalms those engaged in a battle.")], locations: []),
        
        Pokemon(name: "Charmander", nationalDexNum: "004", type1: "Fire", type2: "", speciesName: "Lizard", height: 0.6, weight: 8.5, ability1: "Blaze", ability2: "", hiddenAbility: "Solar Power", EVYield: "1 Speed", catchRate: 45, baseFriendship: 70, baseEXP: 62, growthRate: "Medium Slow", eggGroups: ["Dragon", "Monster"], maleRate: 87.5, eggCycles: 20, baseStats: [39, 52, 43, 60, 50, 65], evolutions: [Evolution(level: 1, pokemon: "Charmander", method: "", treeLevel: 1), Evolution(level: 16, pokemon: "Charmeleon", method: "Level Up", treeLevel: 2), Evolution(level: 36, pokemon: "Charizard", method: "Level Up", treeLevel: 3)], dexEntries: [DexEntry(source: "Pokémon Sword", entry: "It has a preference for hot things. When it rains, steam is said to spout from the tip of its tail."), DexEntry(source: "Pokémon Shield", entry: "From the time it is born, a flame burns at the tip of its tail. Its life would end if the flame were to go out.")], locations: ["Wedgehurst (gift)"]),
        
        Pokemon(name: "Charmeleon", nationalDexNum: "005", type1: "Fire", type2: "", speciesName: "Flame", height: 1.1, weight: 19.0, ability1: "Blaze", ability2: "", hiddenAbility: "Solar Power", EVYield: "1 Sp. Atk, 1 Speed", catchRate: 45, baseFriendship: 70, baseEXP: 142, growthRate: "Medium Slow", eggGroups: ["Dragon", "Monster"], maleRate: 87.5, eggCycles: 20, baseStats: [58, 64, 58, 80, 65, 80], evolutions: [Evolution(level: 1, pokemon: "Charmander", method: "", treeLevel: 1), Evolution(level: 16, pokemon: "Charmeleon", method: "Level Up", treeLevel: 2), Evolution(level: 36, pokemon: "Charizard", method: "Level Up", treeLevel: 3)], dexEntries: [DexEntry(source: "Pokémon Sword", entry: "It has a barbaric nature. In battle, it whips its fiery tail around and slashes away with sharp claws."), DexEntry(source: "Pokémon Shield", entry: "If it becomes agitated during battle, it spouts intense flames, incinerating its surroundings.")], locations: []),
        
        Pokemon(name: "Charizard", nationalDexNum: "006", type1: "Fire", type2: "Flying", speciesName: "Flame", height: 1.7, weight: 90.5, ability1: "Blaze", ability2: "", hiddenAbility: "Solar Power", EVYield: "3 Sp. Atk", catchRate: 45, baseFriendship: 70, baseEXP: 240, growthRate: "Medium Slow", eggGroups: ["Dragon", "Monster"], maleRate: 87.5, eggCycles: 20, baseStats: [78, 84, 78, 109, 85, 100], evolutions: [Evolution(level: 1, pokemon: "Charmander", method: "", treeLevel: 1), Evolution(level: 16, pokemon: "Charmeleon", method: "Level Up", treeLevel: 2), Evolution(level: 36, pokemon: "Charizard", method: "Level Up", treeLevel: 3)], dexEntries: [DexEntry(source: "Pokémon Sword", entry: "It spits fire that is hot enough to melt boulders. It may cause forest fires by blowing flames."), DexEntry(source: "Pokémon Shield", entry: "Its wings can carry this Pokémon close to an altitude of 4,600 feet. It blows out fire at very high temperatures.")], locations: []),
        
        Pokemon(name: "Charizard-Mega-X", nationalDexNum: "006", type1: "Fire", type2: "Dragon", speciesName: "Flame", height: 1.7, weight: 110.5, ability1: "Tough Claws", ability2: "", hiddenAbility: "", EVYield: "3 Sp. Atk", catchRate: 45, baseFriendship: 70, baseEXP: 285, growthRate: "Medium Slow", eggGroups: ["Dragon", "Monster"], maleRate: 87.5, eggCycles: 20, baseStats: [78, 130, 111, 130, 85, 100], evolutions: [Evolution(level: 1, pokemon: "Charmander", method: "", treeLevel: 1), Evolution(level: 16, pokemon: "Charmeleon", method: "Level Up", treeLevel: 2), Evolution(level: 36, pokemon: "Charizard", method: "Level Up", treeLevel: 3)], dexEntries: [DexEntry(source: "Pokémon Let's Go", entry: "The overwhelming power that fills its entire body causes it to turn black and create intense blue flames."), DexEntry(source: "Pokémon Sword", entry: "It spits fire that is hot enough to melt boulders. It may cause forest fires by blowing flames."), DexEntry(source: "Pokémon Shield", entry: "Its wings can carry this Pokémon close to an altitude of 4,600 feet. It blows out fire at very high temperatures.")], locations: []),
        
        Pokemon(name: "Charizard-Mega-Y", nationalDexNum: "006", type1: "Fire", type2: "Flying", speciesName: "Flame", height: 1.7, weight: 100.5, ability1: "Drought", ability2: "", hiddenAbility: "", EVYield: "3 Sp. Atk", catchRate: 45, baseFriendship: 70, baseEXP: 285, growthRate: "Medium Slow", eggGroups: ["Dragon", "Monster"], maleRate: 87.5, eggCycles: 20, baseStats: [78, 104, 78, 159, 115, 100], evolutions: [Evolution(level: 1, pokemon: "Charmander", method: "", treeLevel: 1), Evolution(level: 16, pokemon: "Charmeleon", method: "Level Up", treeLevel: 2), Evolution(level: 36, pokemon: "Charizard", method: "Level Up", treeLevel: 3)], dexEntries: [DexEntry(source: "Pokémon Let's Go", entry: "Its bond with its Trainer is the source of its power. It boasts speed and maneuverability greater than that of a jet fighter."), DexEntry(source: "Pokémon Sword", entry: "It spits fire that is hot enough to melt boulders. It may cause forest fires by blowing flames."), DexEntry(source: "Pokémon Shield", entry: "Its wings can carry this Pokémon close to an altitude of 4,600 feet. It blows out fire at very high temperatures.")], locations: []),
        
        Pokemon(name: "Squirtle", nationalDexNum: "007", type1: "Water", type2: "", speciesName: "Tiny Turtle", height: 0.5, weight: 9.0, ability1: "Torrent", ability2: "", hiddenAbility: "Rain Dish", EVYield: "1 Defense", catchRate: 45, baseFriendship: 70, baseEXP: 63, growthRate: "Medium Slow", eggGroups: ["Monster", "Water 1"], maleRate: 87.5, eggCycles: 20, baseStats: [44, 48, 65, 50, 64, 43], evolutions: [Evolution(level: 1, pokemon: "Squirtle", method: "", treeLevel: 1), Evolution(level: 16, pokemon: "Wartortle", method: "Level Up", treeLevel: 2), Evolution(level: 36, pokemon: "Blastoise", method: "Level Up", treeLevel: 3)], dexEntries: [DexEntry(source: "Pokémon Sword", entry: "When it retracts its long neck into its shell, it squirts out water with vigorous force."), DexEntry(source: "Pokémon Shield", entry: "When it feels threatened, it draws its limbs inside its shell and sprays water from its mouth.")], locations: ["Master Dojo (gift)"]),
        
        Pokemon(name: "Wartortle", nationalDexNum: "008", type1: "Water", type2: "", speciesName: "Turtle", height: 1.0, weight: 22.5, ability1: "Torrent", ability2: "", hiddenAbility: "Rain Dish", EVYield: "1 Defense, 1 Sp. Def", catchRate: 45, baseFriendship: 70, baseEXP: 142, growthRate: "Medium Slow", eggGroups: ["Monster", "Water 1"], maleRate: 87.5, eggCycles: 20, baseStats: [59, 63, 80, 65, 80, 58], evolutions: [Evolution(level: 1, pokemon: "Squirtle", method: "", treeLevel: 1), Evolution(level: 16, pokemon: "Wartortle", method: "Level Up", treeLevel: 2), Evolution(level: 36, pokemon: "Blastoise", method: "Level Up", treeLevel: 3)], dexEntries: [DexEntry(source: "Pokémon Sword", entry: "It is recognized as a symbol of longevity. If its shell has algae on it, that Wartortle is very old."), DexEntry(source: "Pokémon Shield", entry: "It cleverly controls its furry ears and tail to maintain its balance while swimming.")], locations: []),
        
        Pokemon(name: "Blastoise", nationalDexNum: "009", type1: "Water", type2: "", speciesName: "Shellfish", height: 1.6, weight: 85.5, ability1: "Torrent", ability2: "", hiddenAbility: "Rain Dish", EVYield: "3 Sp. Def", catchRate: 45, baseFriendship: 70, baseEXP: 239, growthRate: "Medium Slow", eggGroups: ["Monster", "Water 1"], maleRate: 87.5, eggCycles: 20, baseStats: [79, 83, 100, 85, 105, 78], evolutions: [Evolution(level: 1, pokemon: "Squirtle", method: "", treeLevel: 1), Evolution(level: 16, pokemon: "Wartortle", method: "Level Up", treeLevel: 2), Evolution(level: 36, pokemon: "Blastoise", method: "Level Up", treeLevel: 3)], dexEntries: [DexEntry(source: "Pokémon Sword", entry: "It crushes its foe under its heavy body to cause fainting. In a pinch, it will withdraw inside its shell."), DexEntry(source: "Pokémon Shield", entry: "The rocket cannons on its shell fire jets of water capable of punching holes through thick steel.")], locations: []),
        
        Pokemon(name: "Blastoise-Mega", nationalDexNum: "009", type1: "Water", type2: "", speciesName: "Shellfish", height: 1.6, weight: 101.1, ability1: "Mega Launcher", ability2: "", hiddenAbility: "", EVYield: "3 Sp. Def", catchRate: 45, baseFriendship: 70, baseEXP: 284, growthRate: "Medium Slow", eggGroups: ["Monster", "Water 1"], maleRate: 87.5, eggCycles: 20, baseStats: [79, 103, 120, 135, 115, 78], evolutions: [Evolution(level: 1, pokemon: "Squirtle", method: "", treeLevel: 1), Evolution(level: 16, pokemon: "Wartortle", method: "Level Up", treeLevel: 2), Evolution(level: 36, pokemon: "Blastoise", method: "Level Up", treeLevel: 3)], dexEntries: [DexEntry(source: "Pokémon Let's Go", entry: "The cannon on its back is as powerful as a tank gun. Its tough legs and back enable it to withstand the recoil from firing the cannon."), DexEntry(source: "Pokémon Sword", entry: "It crushes its foe under its heavy body to cause fainting. In a pinch, it will withdraw inside its shell."), DexEntry(source: "Pokémon Shield", entry: "The rocket cannons on its shell fire jets of water capable of punching holes through thick steel.")], locations: []),
        
        Pokemon(name: "Caterpie", nationalDexNum: "010", type1: "Bug", type2: "", speciesName: "Worm", height: 0.3, weight: 2.9, ability1: "Shield Dust", ability2: "", hiddenAbility: "Run Away", EVYield: "1 HP", catchRate: 255, baseFriendship: 70, baseEXP: 39, growthRate: "Medium Fast", eggGroups: ["Bug", ""], maleRate: 50, eggCycles: 15, baseStats: [45, 30, 35, 20, 20, 45], evolutions: [Evolution(level: 1, pokemon: "Caterpie", method: "", treeLevel: 1), Evolution(level: 7, pokemon: "Metapod", method: "Level Up", treeLevel: 2), Evolution(level: 10, pokemon: "Butterfree", method: "Level Up", treeLevel: 3)], dexEntries: [DexEntry(source: "Pokémon Sword", entry: "For protection, it releases a horrible stench from the antenna on its head to drive away enemies."), DexEntry(source: "Pokémon Shield", entry: "Its short feet are tipped with suction pads that enable it to tirelessly climb slopes and walls.")], locations: ["Route 1"]),
        
        Pokemon(name: "Metapod", nationalDexNum: "011", type1: "Bug", type2: "", speciesName: "Cocoon", height: 0.7, weight: 9.9, ability1: "Shed Skin", ability2: "", hiddenAbility: "", EVYield: "2 Defense", catchRate: 120, baseFriendship: 70, baseEXP: 72, growthRate: "Medium Fast", eggGroups: ["Bug", ""], maleRate: 50, eggCycles: 15, baseStats: [50, 20, 55, 25, 25, 30], evolutions: [Evolution(level: 1, pokemon: "Caterpie", method: "", treeLevel: 1), Evolution(level: 7, pokemon: "Metapod", method: "Level Up", treeLevel: 2), Evolution(level: 10, pokemon: "Butterfree", method: "Level Up", treeLevel: 3)], dexEntries: [DexEntry(source: "Pokémon Sword", entry: "It is waiting for the moment to evolve. At this stage, it can only harden, so it remains motionless to avoid attack."), DexEntry(source: "Pokémon Shield", entry: "Even though it is encased in a sturdy shell, the body inside is tender. It can’t withstand a harsh attack.")], locations: ["Rolling Fields"]),
        
        Pokemon(name: "Butterfree", nationalDexNum: "012", type1: "Bug", type2: "Flying", speciesName: "Butterfly", height: 1.1, weight: 32.0, ability1: "Compound Eyes", ability2: "", hiddenAbility: "Tinted Lens", EVYield: "2 Sp. Atk, 1 Sp. Def", catchRate: 45, baseFriendship: 70, baseEXP: 178, growthRate: "Medium Fast", eggGroups: ["Bug", ""], maleRate: 50, eggCycles: 15, baseStats: [60, 45, 50, 90, 80, 70], evolutions: [Evolution(level: 1, pokemon: "Caterpie", method: "", treeLevel: 1), Evolution(level: 7, pokemon: "Metapod", method: "Level Up", treeLevel: 2), Evolution(level: 10, pokemon: "Butterfree", method: "Level Up", treeLevel: 3)], dexEntries: [DexEntry(source: "Pokémon Sword", entry: "In battle, it flaps its wings at great speed to release highly toxic dust into the air."), DexEntry(source: "Pokémon Shield", entry: "It collects honey every day. It rubs honey onto the hairs on its legs to carry it back to its nest.")], locations: ["Rolling Fields", "East Lake Axewell", "Slumbering Weald", "Giant's Mirror"]),
        
        Pokemon(name: "Weedle", nationalDexNum: "013", type1: "Bug", type2: "Poison", speciesName: "Hairy Bug", height: 0.3, weight: 3.2, ability1: "Shield Dust", ability2: "", hiddenAbility: "Run Away", EVYield: "1 Speed", catchRate: 255, baseFriendship: 70, baseEXP: 39, growthRate: "Medium Fast", eggGroups: ["Bug", ""], maleRate: 50, eggCycles: 15, baseStats: [40, 35, 30, 20, 20, 50], evolutions: [Evolution(level: 1, pokemon: "Weedle", method: "", treeLevel: 1), Evolution(level: 7, pokemon: "Kakuna", method: "Level Up", treeLevel: 2), Evolution(level: 10, pokemon: "Beedrill", method: "Level Up", treeLevel: 3)], dexEntries: [DexEntry(source: "Pokémon X", entry: "Often found in forests and grasslands. It has a sharp, toxic barb of around two inches on top of its head."), DexEntry(source: "Pokémon Y", entry: "Its poison stinger is very powerful. Its bright-colored body is intended to warn off its enemies.")], locations: []),
        
        Pokemon(name: "Kakuna", nationalDexNum: "014", type1: "Bug", type2: "Poison", speciesName: "Cocoon", height: 0.6, weight: 10.0, ability1: "Shed Skin", ability2: "", hiddenAbility: "", EVYield: "2 Defense", catchRate: 120, baseFriendship: 70, baseEXP: 72, growthRate: "Medium Fast", eggGroups: ["Bug", ""], maleRate: 50, eggCycles: 15, baseStats: [45, 25, 50, 25, 25, 35], evolutions: [Evolution(level: 1, pokemon: "Weedle", method: "", treeLevel: 1), Evolution(level: 7, pokemon: "Kakuna", method: "Level Up", treeLevel: 2), Evolution(level: 10, pokemon: "Beedrill", method: "Level Up", treeLevel: 3)], dexEntries: [DexEntry(source: "Pokémon X", entry: "Almost incapable of moving, this Pokémon can only harden its shell to protect itself when it is in danger."), DexEntry(source: "Pokémon Y", entry: "While awaiting evolution, it hides from predators under leaves and in nooks of branches.")], locations: []),
        
        Pokemon(name: "Beedrill", nationalDexNum: "015", type1: "Bug", type2: "Poison", speciesName: "Poison Bee", height: 1.0, weight: 29.5, ability1: "Swarm", ability2: "", hiddenAbility: "Sniper", EVYield: "2 Attack, 1 Sp. Def", catchRate: 45, baseFriendship: 70, baseEXP: 178, growthRate: "Medium Fast", eggGroups: ["Bug", ""], maleRate: 50, eggCycles: 15, baseStats: [65, 90, 40, 45, 80, 75], evolutions: [Evolution(level: 1, pokemon: "Weedle", method: "", treeLevel: 1), Evolution(level: 7, pokemon: "Kakuna", method: "Level Up", treeLevel: 2), Evolution(level: 10, pokemon: "Beedrill", method: "Level Up", treeLevel: 3)], dexEntries: [DexEntry(source: "Pokémon X", entry: "It has three poisonous stingers on its forelegs and its tail. They are used to jab its enemy repeatedly."), DexEntry(source: "Pokémon Y", entry: "May appear in a swarm. Flies at violent speeds, all the while stabbing with the toxic stinger on its rear.")], locations: []),
        
        Pokemon(name: "Beedrill-Mega", nationalDexNum: "015", type1: "Bug", type2: "Poison", speciesName: "Poison Bee", height: 1.4, weight: 40.5, ability1: "Adaptability", ability2: "", hiddenAbility: "", EVYield: "2 Attack, 1 Sp. Def", catchRate: 45, baseFriendship: 70, baseEXP: 223, growthRate: "Medium Fast", eggGroups: ["Bug", ""], maleRate: 50, eggCycles: 15, baseStats: [65, 150, 40, 15, 80, 145], evolutions: [Evolution(level: 1, pokemon: "Weedle", method: "", treeLevel: 1), Evolution(level: 7, pokemon: "Kakuna", method: "Level Up", treeLevel: 2), Evolution(level: 10, pokemon: "Beedrill", method: "Level Up", treeLevel: 3)], dexEntries: [DexEntry(source: "Pokémon Let's Go", entry: "Its legs have become poison stingers. It stabs its prey repeatedly with the stingers on its limbs, dealing the final blow with the stinger on its rear."), DexEntry(source: "Pokémon X", entry: "It has three poisonous stingers on its forelegs and its tail. They are used to jab its enemy repeatedly."), DexEntry(source: "Pokémon Y", entry: "May appear in a swarm. Flies at violent speeds, all the while stabbing with the toxic stinger on its rear.")], locations: []),
        
        Pokemon(name: "Pidgey", nationalDexNum: "016", type1: "Normal", type2: "Flying", speciesName: "Tiny Bird", height: 0.3, weight: 1.8, ability1: "Keen Eye", ability2: "Tangled Feet", hiddenAbility: "Big Pecks", EVYield: "1 Speed", catchRate: 255, baseFriendship: 70, baseEXP: 50, growthRate: "Medium Slow", eggGroups: ["Flying", ""], maleRate: 50, eggCycles: 15, baseStats: [40, 45, 40, 35, 35, 56], evolutions: [Evolution(level: 1, pokemon: "Pidgey", method: "", treeLevel: 1), Evolution(level: 18, pokemon: "Pidgeotto", method: "Level Up", treeLevel: 2), Evolution(level: 36, pokemon: "Pidgeot", method: "Level Up", treeLevel: 3)], dexEntries: [DexEntry(source: "Pokémon X", entry: "A common sight in forests and woods. It flaps its wings at ground level to kick up blinding sand."), DexEntry(source: "Pokémon Y", entry: "It is docile and prefers to avoid conflict. If disturbed, however, it can ferociously strike back.")], locations: []),
        
        Pokemon(name: "Pidgeotto", nationalDexNum: "017", type1: "Normal", type2: "Flying", speciesName: "Bird", height: 1.1, weight: 30.0, ability1: "Keen Eye", ability2: "Tangled Feet", hiddenAbility: "Big Pecks", EVYield: "2 Speed", catchRate: 120, baseFriendship: 70, baseEXP: 122, growthRate: "Medium Slow", eggGroups: ["Flying", ""], maleRate: 50, eggCycles: 15, baseStats: [63, 60, 55, 50, 50, 71], evolutions: [Evolution(level: 1, pokemon: "Pidgey", method: "", treeLevel: 1), Evolution(level: 18, pokemon: "Pidgeotto", method: "Level Up", treeLevel: 2), Evolution(level: 36, pokemon: "Pidgeot", method: "Level Up", treeLevel: 3)], dexEntries: [DexEntry(source: "Pokémon X", entry: "The claws on its feet are well developed. It can carry prey such as an Exeggcute to its nest over 60 miles away."), DexEntry(source: "Pokémon Y", entry: "Very protective of its sprawling territorial area, this Pokémon will fiercely peck at any intruder.")], locations: []),
        
        Pokemon(name: "Pidgeot", nationalDexNum: "018", type1: "Normal", type2: "Flying", speciesName: "Bird", height: 1.5, weight: 39.5, ability1: "Keen Eye", ability2: "Tangled Feet", hiddenAbility: "Big Pecks", EVYield: "3 Speed", catchRate: 45, baseFriendship: 70, baseEXP: 216, growthRate: "Medium Slow", eggGroups: ["Flying", ""], maleRate: 50, eggCycles: 15, baseStats: [83, 80, 75, 70, 70, 101], evolutions: [Evolution(level: 1, pokemon: "Pidgey", method: "", treeLevel: 1), Evolution(level: 18, pokemon: "Pidgeotto", method: "Level Up", treeLevel: 2), Evolution(level: 36, pokemon: "Pidgeot", method: "Level Up", treeLevel: 3)], dexEntries: [DexEntry(source: "Pokémon X", entry: "When hunting, it skims the surface of water at high speed to pick off unwary prey such as Magikarp."), DexEntry(source: "Pokémon Y", entry: "It spreads its gorgeous wings widely to intimidate enemies. It races through the skies at Mach-2 speed.")], locations: []),
        
        Pokemon(name: "Pidgeot-Mega", nationalDexNum: "018", type1: "Normal", type2: "Flying", speciesName: "Bird", height: 2.2, weight: 50.5, ability1: "No Guard", ability2: "", hiddenAbility: "", EVYield: "3 Speed", catchRate: 45, baseFriendship: 70, baseEXP: 261, growthRate: "Medium Slow", eggGroups: ["Flying", ""], maleRate: 50, eggCycles: 15, baseStats: [83, 80, 80, 135, 80, 121], evolutions: [Evolution(level: 1, pokemon: "Pidgey", method: "", treeLevel: 1), Evolution(level: 18, pokemon: "Pidgeotto", method: "Level Up", treeLevel: 2), Evolution(level: 36, pokemon: "Pidgeot", method: "Level Up", treeLevel: 3)], dexEntries: [DexEntry(source: "Pokémon Let's Go", entry: "With its muscular strength now greatly increased, it can fly continuously for two weeks without resting."), DexEntry(source: "Pokémon X", entry: "When hunting, it skims the surface of water at high speed to pick off unwary prey such as Magikarp."), DexEntry(source: "Pokémon Y", entry: "It spreads its gorgeous wings widely to intimidate enemies. It races through the skies at Mach-2 speed.")], locations: []),
        
        Pokemon(name: "Rattata", nationalDexNum: "019", type1: "Normal", type2: "", speciesName: "Mouse", height: 0.3, weight: 3.5, ability1: "Run Away", ability2: "Guts", hiddenAbility: "Hustle", EVYield: "1 Speed", catchRate: 255, baseFriendship: 70, baseEXP: 51, growthRate: "Medium Fast", eggGroups: ["Field", ""], maleRate: 50, eggCycles: 15, baseStats: [30, 56, 35, 25, 35, 72], evolutions: [Evolution(level: 1, pokemon: "Rattata", method: "", treeLevel: 1), Evolution(level: 20, pokemon: "Raticate", method: "Level Up", treeLevel: 2)], dexEntries: [DexEntry(source: "Pokémon Ultra Sun", entry: "Its incisors grow continuously throughout its life. If its incisors get too long, this Pokémon becomes unable to eat, and it starves to death."), DexEntry(source: "Pokémon Ultra Moon", entry: "This Pokémon is common but hazardous. Its sharp incisors can easily cut right through hard wood.")], locations: []),
        
        Pokemon(name: "Rattata-Alola", nationalDexNum: "019", type1: "Dark", type2: "Normal", speciesName: "Mouse", height: 0.3, weight: 3.8, ability1: "Gluttony", ability2: "Hustle", hiddenAbility: "Thick Fat", EVYield: "1 Speed", catchRate: 255, baseFriendship: 70, baseEXP: 51, growthRate: "Medium Fast", eggGroups: ["Field", ""], maleRate: 50, eggCycles: 15, baseStats: [30, 56, 35, 25, 35, 72], evolutions: [Evolution(level: 1, pokemon: "Rattata-Alola", method: "", treeLevel: 1), Evolution(level: 20, pokemon: "Raticate-Alola", method: "Level Up", treeLevel: 2)], dexEntries: [DexEntry(source: "Pokémon Ultra Sun", entry: "It shows no interest in anything that isn’t fresh. If you take it shopping with you, it will help you pick out ingredients."), DexEntry(source: "Pokémon Ultra Moon", entry: "Night after night, they sneak into people’s homes seeking food. A massive outbreak of them has become an issue of public concern.")], locations: []),
        
        Pokemon(name: "Raticate", nationalDexNum: "020", type1: "Normal", type2: "", speciesName: "Mouse", height: 0.7, weight: 18.5, ability1: "Run Away", ability2: "Guts", hiddenAbility: "Hustle", EVYield: "2 Speed", catchRate: 127, baseFriendship: 70, baseEXP: 145, growthRate: "Medium Fast", eggGroups: ["Field", ""], maleRate: 50, eggCycles: 15, baseStats: [55, 81, 60, 50, 70, 97], evolutions: [Evolution(level: 1, pokemon: "Rattata", method: "", treeLevel: 1), Evolution(level: 20, pokemon: "Raticate", method: "Level Up", treeLevel: 2)], dexEntries: [DexEntry(source: "Pokémon Ultra Sun", entry: "People say that it fled from its enemies by using its small webbed hind feet to swim from island to island in Alola."), DexEntry(source: "Pokémon Ultra Moon", entry: "Its whiskers are essential for maintaining its balance. No matter how friendly you are, it will get angry and bite you if you touch its whiskers.")], locations: []),
        
        Pokemon(name: "Raticate-Alola", nationalDexNum: "020", type1: "Dark", type2: "Normal", speciesName: "Mouse", height: 0.7, weight: 25.5, ability1: "Gluttony", ability2: "Hustle", hiddenAbility: "Thick Fat", EVYield: "2 Speed", catchRate: 127, baseFriendship: 70, baseEXP: 145, growthRate: "Medium Fast", eggGroups: ["Field", ""], maleRate: 50, eggCycles: 15, baseStats: [75, 71, 70, 40, 80, 77], evolutions: [Evolution(level: 1, pokemon: "Rattata-Alola", method: "", treeLevel: 1), Evolution(level: 20, pokemon: "Raticate-Alola", method: "Level Up", treeLevel: 2)], dexEntries: [DexEntry(source: "Pokémon Ultra Sun", entry: "It has an incredibly greedy personality. Its nest is filled with so much food gathered by Rattata at its direction, it can’t possibly eat it all."), DexEntry(source: "Pokémon Ultra Moon", entry: "It commands a nest of Rattata. Different nests don’t get along, whipping up severe fights over feeding grounds.")], locations: []),
        
        Pokemon(name: "Spearow", nationalDexNum: "021", type1: "Normal", type2: "Flying", speciesName: "Tiny Bird", height: 0.3, weight: 2.0, ability1: "Keen Eye", ability2: "", hiddenAbility: "Sniper", EVYield: "1 Speed", catchRate: 255, baseFriendship: 70, baseEXP: 52, growthRate: "Medium Fast", eggGroups: ["Flying", ""], maleRate: 50, eggCycles: 15, baseStats: [40, 60, 30, 31, 31, 70], evolutions: [Evolution(level: 1, pokemon: "Spearow", method: "", treeLevel: 1), Evolution(level: 20, pokemon: "Fearow", method: "Level Up", treeLevel: 2)], dexEntries: [DexEntry(source: "Pokémon Ultra Sun", entry: "Its reckless nature leads it to stand up to others—even large Pokémon—if it has to protect its territory."), DexEntry(source: "Pokémon Ultra Moon", entry: "Due to its short wings, it can’t fly long distances. It wanders about restlessly and pecks at bug Pokémon.")], locations: []),
        
        Pokemon(name: "Fearow", nationalDexNum: "022", type1: "Normal", type2: "Flying", speciesName: "Beak", height: 1.2, weight: 38.0, ability1: "Keen Eye", ability2: "", hiddenAbility: "Sniper", EVYield: "2 Speed", catchRate: 90, baseFriendship: 70, baseEXP: 155, growthRate: "Medium Fast", eggGroups: ["Flying", ""], maleRate: 50, eggCycles: 15, baseStats: [65, 90, 65, 61, 61, 100], evolutions: [Evolution(level: 1, pokemon: "Spearow", method: "", treeLevel: 1), Evolution(level: 20, pokemon: "Fearow", method: "Level Up", treeLevel: 2)], dexEntries: [DexEntry(source: "Pokémon Ultra Sun", entry: "Carrying food through Fearow’s territory is dangerous. It will snatch the food away from you in a flash!"), DexEntry(source: "Pokémon Ultra Moon", entry: "In Alola, fish Pokémon are its prey. It can be seen circling above the ocean searching for food.")], locations: []),
        
        Pokemon(name: "Ekans", nationalDexNum: "023", type1: "Poison", type2: "", speciesName: "Snake", height: 2.0, weight: 6.9, ability1: "Intimidate", ability2: "Shed Skin", hiddenAbility: "Unnerve", EVYield: "1 Attack", catchRate: 255, baseFriendship: 70, baseEXP: 58, growthRate: "Medium Fast", eggGroups: ["Dragon", "Field"], maleRate: 50, eggCycles: 20, baseStats: [35, 60, 44, 40, 54, 55], evolutions: [Evolution(level: 1, pokemon: "Ekans", method: "", treeLevel: 1), Evolution(level: 22, pokemon: "Arbok", method: "Level Up", treeLevel: 2)], dexEntries: [DexEntry(source: "Pokémon Ultra Sun", entry: "By dislocating its jaw, it can swallow prey larger than itself. After a meal, it curls up and rests."), DexEntry(source: "Pokémon Ultra Moon", entry: "The eggs of bird Pokémon are its favorite food. It swallows eggs whole, so sometimes an egg gets stuck, and Ekans faints.")], locations: []),
        
        Pokemon(name: "Arbok", nationalDexNum: "024", type1: "Poison", type2: "", speciesName: "Cobra", height: 3.5, weight: 65.0, ability1: "Intimidate", ability2: "Shed Skin", hiddenAbility: "Unnerve", EVYield: "2 Attack", catchRate: 90, baseFriendship: 70, baseEXP: 157, growthRate: "Medium Fast", eggGroups: ["Dragon", "Field"], maleRate: 50, eggCycles: 20, baseStats: [60, 95, 69, 65, 79, 80], evolutions: [Evolution(level: 1, pokemon: "Ekans", method: "", treeLevel: 1), Evolution(level: 22, pokemon: "Arbok", method: "Level Up", treeLevel: 2)], dexEntries: [DexEntry(source: "Pokémon Ultra Sun", entry: "The latest research has determined that there are over 20 possible arrangements of the patterns on its stomach."), DexEntry(source: "Pokémon Ultra Moon", entry: "After stunning its opponents with the pattern on its stomach, it quickly wraps them up in its body and waits for them to stop moving.")], locations: []),
        
        Pokemon(name: "Pikachu", nationalDexNum: "025", type1: "Electric", type2: "", speciesName: "Mouse", height: 0.4, weight: 6.0, ability1: "Static", ability2: "", hiddenAbility: "Lightning Rod", EVYield: "2 Speed", catchRate: 190, baseFriendship: 70, baseEXP: 112, growthRate: "Medium Fast", eggGroups: ["Fairy", "Field"], maleRate: 50, eggCycles: 10, baseStats: [35, 55, 40, 50, 50, 90], evolutions: [Evolution(level: 1, pokemon: "Pikachu", method: "", treeLevel: 1), Evolution(level: 1, pokemon: "Raichu", method: "Thunder Stone", treeLevel: 2)], dexEntries: [DexEntry(source: "Pokémon Sword", entry: "Pikachu that can generate powerful electricity have cheek sacs that are extra soft and super stretchy."), DexEntry(source: "Pokémon Shield", entry: "When Pikachu meet, they’ll touch their tails together and exchange electricity through them as a form of greeting.")], locations: ["Route 4", "Stony Wilderness", "Forest of Focus"]),
        
        Pokemon(name: "Raichu", nationalDexNum: "026", type1: "Electric", type2: "", speciesName: "Mouse", height: 0.8, weight: 30.0, ability1: "Static", ability2: "", hiddenAbility: "Lightning Rod", EVYield: "3 Speed", catchRate: 75, baseFriendship: 70, baseEXP: 218, growthRate: "Medium Fast", eggGroups: ["Fairy", "Field"], maleRate: 50, eggCycles: 10, baseStats: [60, 90, 55, 90, 80, 110], evolutions: [Evolution(level: 1, pokemon: "Pikachu", method: "", treeLevel: 1), Evolution(level: 1, pokemon: "Raichu", method: "Thunder Stone", treeLevel: 2)], dexEntries: [DexEntry(source: "Pokémon Sword", entry: "Its long tail serves as a ground to protect itself from its own high-voltage power."), DexEntry(source: "Pokémon Shield", entry: "If its electric pouches run empty, it raises its tail to gather electricity from the atmosphere.")], locations: []),
        
        Pokemon(name: "Raichu-Alola", nationalDexNum: "026", type1: "Electric", type2: "Psychic", speciesName: "Mouse", height: 0.7, weight: 21.0, ability1: "Surge Surfer", ability2: "", hiddenAbility: "", EVYield: "3 Speed", catchRate: 75, baseFriendship: 70, baseEXP: 218, growthRate: "Medium Fast", eggGroups: ["Fairy", "Field"], maleRate: 50, eggCycles: 10, baseStats: [60, 85, 50, 95, 85, 110], evolutions: [Evolution(level: 1, pokemon: "Pikachu", method: "", treeLevel: 1), Evolution(level: 1, pokemon: "Raichu-Alola", method: "Thunder Stone in Alola", treeLevel: 2)], dexEntries: [DexEntry(source: "Pokémon Sword", entry: "It’s believed that the weather, climate, and food of the Alola region all play a part in causing Pikachu to evolve into this form of Raichu."), DexEntry(source: "Pokémon Shield", entry: "This Pokémon rides on its tail while it uses its psychic powers to levitate. It attacks with star-shaped thunderbolts.")], locations: []),
        
        Pokemon(name: "Sandshrew", nationalDexNum: "027", type1: "Ground", type2: "", speciesName: "Mouse", height: 0.6, weight: 12.0, ability1: "Sand Veil", ability2: "", hiddenAbility: "Sand Rush", EVYield: "1 Defense", catchRate: 255, baseFriendship: 70, baseEXP: 60, growthRate: "Medium Fast", eggGroups: ["Field", ""], maleRate: 50, eggCycles: 20, baseStats: [50, 75, 85, 20, 30, 40], evolutions: [Evolution(level: 1, pokemon: "Sandshrew", method: "", treeLevel: 1), Evolution(level: 22, pokemon: "Sandslash", method: "Level Up", treeLevel: 2)], dexEntries: [DexEntry(source: "Pokémon Sword", entry: "It loves to bathe in the grit of dry, sandy areas. By sand bathing, the Pokémon rids itself of dirt and moisture clinging to its body."), DexEntry(source: "Pokémon Shield", entry: "It burrows into the ground to create its nest. If hard stones impede its tunneling, it uses its sharp claws to shatter them and then carries on digging.")], locations: ["Warm-Up Tunnel"]),
        
        Pokemon(name: "Sandshrew-Alola", nationalDexNum: "027", type1: "Ice", type2: "Steel", speciesName: "Mouse", height: 0.7, weight: 40.0, ability1: "Snow Cloak", ability2: "", hiddenAbility: "Slush Rush", EVYield: "1 Defense", catchRate: 255, baseFriendship: 70, baseEXP: 60, growthRate: "Medium Fast", eggGroups: ["Field", ""], maleRate: 50, eggCycles: 20, baseStats: [50, 75, 90, 10, 35, 40], evolutions: [Evolution(level: 1, pokemon: "Sandshrew-Alola", method: "", treeLevel: 1), Evolution(level: 1, pokemon: "Sandslash-Alola", method: "Ice Stone", treeLevel: 2)], dexEntries: [DexEntry(source: "Pokémon Sword", entry: "Life on mountains covered with deep snow has granted this Pokémon a body of ice that’s as hard as steel."), DexEntry(source: "Pokémon Shield", entry: "It lives in snowy mountains on southern islands. When a blizzard rolls in, this Pokémon hunkers down in the snow to avoid getting blown away.")], locations: ["Warm-Up Tunnel"]),
        
        Pokemon(name: "Sandslash", nationalDexNum: "028", type1: "Ground", type2: "", speciesName: "Mouse", height: 1.0, weight: 29.5, ability1: "Sand Veil", ability2: "", hiddenAbility: "Sand Rush", EVYield: "2 Defense", catchRate: 90, baseFriendship: 70, baseEXP: 158, growthRate: "Medium Fast", eggGroups: ["Field", ""], maleRate: 50, eggCycles: 20, baseStats: [75, 100, 110, 45, 55, 65], evolutions: [Evolution(level: 1, pokemon: "Sandshrew", method: "", treeLevel: 1), Evolution(level: 22, pokemon: "Sandslash", method: "Level Up", treeLevel: 2)], dexEntries: [DexEntry(source: "Pokémon Sword", entry: "The drier the area Sandslash lives in, the harder and smoother the Pokémon’s spikes will feel when touched."), DexEntry(source: "Pokémon Shield", entry: "It climbs trees by hooking on with its sharp claws. Sandslash shares the berries it gathers, dropping them down to Sandshrew waiting below the tree.")], locations: []),
        
        Pokemon(name: "Sandslash-Alola", nationalDexNum: "028", type1: "Ice", type2: "Steel", speciesName: "Mouse", height: 1.2, weight: 55.0, ability1: "Snow Cloak", ability2: "", hiddenAbility: "Slush Rush", EVYield: "2 Defense", catchRate: 90, baseFriendship: 70, baseEXP: 158, growthRate: "Medium Fast", eggGroups: ["Field", ""], maleRate: 50, eggCycles: 20, baseStats: [75, 100, 120, 25, 65, 65], evolutions: [Evolution(level: 1, pokemon: "Sandshrew-Alola", method: "", treeLevel: 1), Evolution(level: 1, pokemon: "Sandslash-Alola", method: "Ice Stone", treeLevel: 2)], dexEntries: [DexEntry(source: "Pokémon Sword", entry: "It uses large, hooked claws to cut a path through deep snow as it runs. On snowy mountains, this Sandslash is faster than any other Pokémon."), DexEntry(source: "Pokémon Shield", entry: "Many people climb snowy mountains, hoping to see the icy spikes of these Pokémon glistening in the light of dawn.")], locations: []),
        
        Pokemon(name: "Nidoran♀", nationalDexNum: "029", type1: "Poison", type2: "", speciesName: "Poison Pin", height: 0.4, weight: 7.0, ability1: "Poison Point", ability2: "Rivalry", hiddenAbility: "Hustle", EVYield: "1 HP", catchRate: 235, baseFriendship: 70, baseEXP: 55, growthRate: "Medium Slow", eggGroups: ["Field", "Monster"], maleRate: 0, eggCycles: 20, baseStats: [55, 47, 52, 40, 40, 41], evolutions: [Evolution(level: 1, pokemon: "Nidoran♀", method: "", treeLevel: 1), Evolution(level: 16, pokemon: "Nidorina", method: "Level Up", treeLevel: 2), Evolution(level: 1, pokemon: "Nidoqueen", method: "Moon Stone", treeLevel: 3)], dexEntries: [DexEntry(source: "Pokémon Sword", entry: "Females are more sensitive to smells than males. While foraging, they’ll use their whiskers to check wind direction and stay downwind of predators."), DexEntry(source: "Pokémon Shield", entry: "It uses its hard incisor teeth to crush and eat berries. The tip of a female Nidoran’s horn is a bit more rounded than the tip of a male’s horn.")], locations: ["Giant's Bed", "Old Cemetery"]),
        
        Pokemon(name: "Nidorina", nationalDexNum: "030", type1: "Poison", type2: "", speciesName: "Poison Pin", height: 0.8, weight: 20.0, ability1: "Poison Point", ability2: "Rivalry", hiddenAbility: "Hustle", EVYield: "2 HP", catchRate: 120, baseFriendship: 70, baseEXP: 128, growthRate: "Medium Slow", eggGroups: ["Undiscovered", ""], maleRate: 0, eggCycles: 20, baseStats: [70, 62, 67, 55, 55, 56], evolutions: [Evolution(level: 1, pokemon: "Nidoran♀", method: "", treeLevel: 1), Evolution(level: 16, pokemon: "Nidorina", method: "Level Up", treeLevel: 2), Evolution(level: 1, pokemon: "Nidoqueen", method: "Moon Stone", treeLevel: 3)], dexEntries: [DexEntry(source: "Pokémon Sword", entry: "The horn on its head has atrophied. It’s thought that this happens so Nidorina’s children won’t get poked while their mother is feeding them."), DexEntry(source: "Pokémon Shield", entry: "If the group is threatened, these Pokémon will band together to assault enemies with a chorus of ultrasonic waves.")], locations: []),
        
        Pokemon(name: "Nidoqueen", nationalDexNum: "031", type1: "Poison", type2: "Ground", speciesName: "Drill", height: 1.3, weight: 60.0, ability1: "Poison Point", ability2: "Rivalry", hiddenAbility: "Hustle", EVYield: "3 HP", catchRate: 45, baseFriendship: 70, baseEXP: 227, growthRate: "Medium Slow", eggGroups: ["Undiscovered", ""], maleRate: 0, eggCycles: 20, baseStats: [90, 92, 87, 75, 85, 76], evolutions: [Evolution(level: 1, pokemon: "Nidoran♀", method: "", treeLevel: 1), Evolution(level: 16, pokemon: "Nidorina", method: "Level Up", treeLevel: 2), Evolution(level: 1, pokemon: "Nidoqueen", method: "Moon Stone", treeLevel: 3)], dexEntries: [DexEntry(source: "Pokémon Sword", entry: "Nidoqueen is better at defense than offense. With scales like armor, this Pokémon will shield its children from any kind of attack."), DexEntry(source: "Pokémon Shield", entry: "It pacifies offspring by placing them in the gaps between the spines on its back. The spines will never secrete poison while young are present.")], locations: []),
        
        Pokemon(name: "Nidoran♂", nationalDexNum: "032", type1: "Poison", type2: "", speciesName: "Poison Pin", height: 0.5, weight: 9.0, ability1: "Poison Point", ability2: "Rivalry", hiddenAbility: "Hustle", EVYield: "1 Attack", catchRate: 235, baseFriendship: 70, baseEXP: 55, growthRate: "Medium Slow", eggGroups: ["Field", "Monster"], maleRate: 100, eggCycles: 20, baseStats: [46, 57, 40, 40, 40, 50], evolutions: [Evolution(level: 1, pokemon: "Nidoran♂", method: "", treeLevel: 1), Evolution(level: 16, pokemon: "Nidorino", method: "Level Up", treeLevel: 2), Evolution(level: 1, pokemon: "Nidoking", method: "Moon Stone", treeLevel: 3)], dexEntries: [DexEntry(source: "Pokémon Sword", entry: "The horn on a male Nidoran’s forehead contains a powerful poison. This is a very cautious Pokémon, always straining its large ears."), DexEntry(source: "Pokémon Shield", entry: "Small but brave, this Pokémon will hold its ground and even risk its life in battle to protect the female it’s friendly with.")], locations: ["Giant's Bed", "Old Cemetery"]),
        
        Pokemon(name: "Nidorino", nationalDexNum: "033", type1: "Poison", type2: "", speciesName: "Poison Pin", height: 0.9, weight: 19.5, ability1: "Poison Point", ability2: "Rivalry", hiddenAbility: "Hustle", EVYield: "2 Attack", catchRate: 120, baseFriendship: 70, baseEXP: 128, growthRate: "Medium Slow", eggGroups: ["Field", "Monster"], maleRate: 100, eggCycles: 20, baseStats: [61, 72, 57, 55, 55, 65], evolutions: [Evolution(level: 1, pokemon: "Nidoran♂", method: "", treeLevel: 1), Evolution(level: 16, pokemon: "Nidorino", method: "Level Up", treeLevel: 2), Evolution(level: 1, pokemon: "Nidoking", method: "Moon Stone", treeLevel: 3)], dexEntries: [DexEntry(source: "Pokémon Sword", entry: "With a horn that’s harder than diamond, this Pokémon goes around shattering boulders as it searches for a moon stone."), DexEntry(source: "Pokémon Shield", entry: "It’s nervous and quick to act aggressively. The potency of its poison increases along with the level of adrenaline present in its body.")], locations: []),
        
        Pokemon(name: "Nidoking", nationalDexNum: "034", type1: "Poison", type2: "Ground", speciesName: "Drill", height: 1.4, weight: 62.0, ability1: "Poison Point", ability2: "Rivalry", hiddenAbility: "Sheer Force", EVYield: "3 Attack", catchRate: 45, baseFriendship: 70, baseEXP: 227, growthRate: "Medium Slow", eggGroups: ["Field", "Monster"], maleRate: 100, eggCycles: 20, baseStats: [81, 102, 77, 85, 75, 85], evolutions: [Evolution(level: 1, pokemon: "Nidoran♂", method: "", treeLevel: 1), Evolution(level: 16, pokemon: "Nidorino", method: "Level Up", treeLevel: 2), Evolution(level: 1, pokemon: "Nidoking", method: "Moon Stone", treeLevel: 3)], dexEntries: [DexEntry(source: "Pokémon Sword", entry: "When it goes on a rampage, it’s impossible to control. But in the presence of a Nidoqueen it’s lived with for a long time, Nidoking calms down."), DexEntry(source: "Pokémon Shield", entry: "Nidoking prides itself on its strength. It’s forceful and spirited in battle, making use of its thick tail and diamond-crushing horn.")], locations: []),
        
        Pokemon(name: "Clefairy", nationalDexNum: "035", type1: "Fairy", type2: "", speciesName: "Fairy", height: 0.6, weight: 7.5, ability1: "Cute Charm", ability2: "Magic Guard", hiddenAbility: "Friend Guard", EVYield: "2 HP", catchRate: 150, baseFriendship: 140, baseEXP: 113, growthRate: "Fast", eggGroups: ["Fairy", ""], maleRate: 25, eggCycles: 10, baseStats: [70, 45, 48, 60, 65, 35], evolutions: [Evolution(level: 1, pokemon: "Clefairy", method: "", treeLevel: 1), Evolution(level: 1, pokemon: "Clefable", method: "Moon Stone", treeLevel: 2)], dexEntries: [DexEntry(source: "Pokémon Sword", entry: "It is said that happiness will come to those who see a gathering of Clefairy dancing under a full moon."), DexEntry(source: "Pokémon Shield", entry: "Its adorable behavior and cry make it highly popular. However, this cute Pokémon is rarely found.")], locations: ["Giant's Cap", "Motostoke Riverbank", "Giant's Bed", "Snowslide Slope", "Tunnel to the Top"]),
        
        Pokemon(name: "Clefable", nationalDexNum: "036", type1: "Fairy", type2: "", speciesName: "Fairy", height: 1.3, weight: 40.0, ability1: "Cute Charm", ability2: "Magic Guard", hiddenAbility: "Unaware", EVYield: "3 HP", catchRate: 25, baseFriendship: 140, baseEXP: 217, growthRate: "Fast", eggGroups: ["Fairy", ""], maleRate: 25, eggCycles: 10, baseStats: [95, 70, 73, 95, 90, 60], evolutions: [Evolution(level: 1, pokemon: "Clefairy", method: "", treeLevel: 1), Evolution(level: 1, pokemon: "Clefable", method: "Moon Stone", treeLevel: 2)], dexEntries: [DexEntry(source: "Pokémon Sword", entry: "A timid fairy Pokémon that is rarely seen, it will run and hide the moment it senses people."), DexEntry(source: "Pokémon Shield", entry: "Their ears are sensitive enough to hear a pin drop from over a mile away, so they’re usually found in quiet places.")], locations: []),
        
        Pokemon(name: "Vulpix", nationalDexNum: "037", type1: "Fire", type2: "", speciesName: "Fox", height: 0.6, weight: 9.9, ability1: "Flash Fire", ability2: "", hiddenAbility: "Drought", EVYield: "1 Speed", catchRate: 190, baseFriendship: 70, baseEXP: 60, growthRate: "Medium Fast", eggGroups: ["Field", ""], maleRate: 25, eggCycles: 20, baseStats: [38, 41, 40, 50, 65, 65], evolutions: [Evolution(level: 1, pokemon: "Vulpix", method: "", treeLevel: 1), Evolution(level: 1, pokemon: "Ninetales", method: "Fire Stone", treeLevel: 2)], dexEntries: [DexEntry(source: "Pokémon Sword", entry: "While young, it has six gorgeous tails. When it grows, several new tails are sprouted."), DexEntry(source: "Pokémon Shield", entry: "As each tail grows, its fur becomes more lustrous. When held, it feels slightly warm.")], locations: ["Dusty Bowl", "Hammerlocke Hills"]),
        
        Pokemon(name: "Vulpix-Alola", nationalDexNum: "037", type1: "Ice", type2: "", speciesName: "Fox", height: 0.6, weight: 9.9, ability1: "Snow Cloak", ability2: "", hiddenAbility: "Snow Warning", EVYield: "1 Speed", catchRate: 190, baseFriendship: 70, baseEXP: 60, growthRate: "Medium Fast", eggGroups: ["Field", ""], maleRate: 25, eggCycles: 20, baseStats: [38, 41, 40, 50, 65, 65], evolutions: [Evolution(level: 1, pokemon: "Vulpix-Alola", method: "", treeLevel: 1), Evolution(level: 1, pokemon: "Ninetales-Alola", method: "Ice Stone", treeLevel: 2)], dexEntries: [DexEntry(source: "Pokémon Sword", entry: "After long years in the ever-snowcapped mountains of Alola, this Vulpix has gained power over ice."), DexEntry(source: "Pokémon Shield", entry: "If you observe its curly hairs through a microscope, you’ll see small ice particles springing up.")], locations: []),
        
        Pokemon(name: "Ninetales", nationalDexNum: "038", type1: "Fire", type2: "", speciesName: "Fox", height: 1.1, weight: 19.9, ability1: "Flash Fire", ability2: "", hiddenAbility: "Drought", EVYield: "1 Sp. Def, 1 Speed", catchRate: 75, baseFriendship: 70, baseEXP: 177, growthRate: "Medium Fast", eggGroups: ["Field", ""], maleRate: 25, eggCycles: 20, baseStats: [73, 76, 75, 81, 100, 100], evolutions: [Evolution(level: 1, pokemon: "Vulpix", method: "", treeLevel: 1), Evolution(level: 1, pokemon: "Ninetales", method: "Fire Stone", treeLevel: 2)], dexEntries: [DexEntry(source: "Pokémon Sword", entry: "It is said to live 1,000 years, and each of its tails is loaded with supernatural powers."), DexEntry(source: "Pokémon Shield", entry: "Very smart and very vengeful. Grabbing one of its many tails could result in a 1,000-year curse.")], locations: []),
        
        Pokemon(name: "Ninetales-Alola", nationalDexNum: "038", type1: "Ice", type2: "Fairy", speciesName: "Fox", height: 1.1, weight: 19.9, ability1: "Snow Cloak", ability2: "", hiddenAbility: "Snow Warning", EVYield: "2 Speed", catchRate: 75, baseFriendship: 70, baseEXP: 177, growthRate: "Medium Fast", eggGroups: ["Field", ""], maleRate: 25, eggCycles: 20, baseStats: [73, 67, 75, 81, 100, 109], evolutions: [Evolution(level: 1, pokemon: "Vulpix-Alola", method: "", treeLevel: 1), Evolution(level: 1, pokemon: "Ninetales-Alola", method: "Ice Stone", treeLevel: 2)], dexEntries: [DexEntry(source: "Pokémon Sword", entry: "A deity resides in the snowy mountains where this Pokémon lives. In ancient times, it was worshiped as that deity’s incarnation."), DexEntry(source: "Pokémon Shield", entry: "While it will guide travelers who get lost on a snowy mountain down to the mountain’s base, it won’t forgive anyone who harms nature.")], locations: []),
        
        Pokemon(name: "Jigglypuff", nationalDexNum: "039", type1: "Normal", type2: "Fairy", speciesName: "Balloon", height: 0.5, weight: 5.5, ability1: "Cute Charm", ability2: "Competitive", hiddenAbility: "Friend Guard", EVYield: "2 HP", catchRate: 170, baseFriendship: 70, baseEXP: 95, growthRate: "Fast", eggGroups: ["Fairy", ""], maleRate: 25, eggCycles: 10, baseStats: [115, 45, 20, 45, 25, 20], evolutions: [Evolution(level: 1, pokemon: "Jigglypuff", method: "", treeLevel: 1), Evolution(level: 1, pokemon: "Wigglytuff", method: "Moon Stone", treeLevel: 2)], dexEntries: [DexEntry(source: "Pokémon Sword", entry: "Jigglypuff has top-notch lung capacity, even by comparison to other Pokémon. It won’t stop singing its lullabies until its foes fall asleep."), DexEntry(source: "Pokémon Shield", entry: "By freely changing the wavelength of its voice, Jigglypuff sings a mysterious melody sure to make any listener sleepy.")], locations: ["Challenge Beach", "Fields of Honor"]),
        
        Pokemon(name: "Wigglytuff", nationalDexNum: "040", type1: "Normal", type2: "Fairy", speciesName: "Balloon", height: 1.0, weight: 12.0, ability1: "Cute Charm", ability2: "Competitive", hiddenAbility: "Frisk", EVYield: "3 HP", catchRate: 50, baseFriendship: 70, baseEXP: 196, growthRate: "Fast", eggGroups: ["Fairy", ""], maleRate: 25, eggCycles: 10, baseStats: [140, 70, 45, 85, 50, 45], evolutions: [Evolution(level: 1, pokemon: "Jigglypuff", method: "", treeLevel: 1), Evolution(level: 1, pokemon: "Wigglytuff", method: "Moon Stone", treeLevel: 2)], dexEntries: [DexEntry(source: "Pokémon Sword", entry: "The more air it takes in, the more it inflates. If opponents catch it in a bad mood, it will inflate itself to an enormous size to intimidate them."), DexEntry(source: "Pokémon Shield", entry: "It’s proud of its fur, which is fine and delicate. In particular, the curl on its forehead has a texture that’s perfectly heavenly.")], locations: [])
    
    ]
    
    static let pokemonList: [Pokemon] = []
    
    static func theTestList() -> [Pokemon] {
        return [
            Pokemon(name: "Bulbasaur", nationalDexNum: "001", type1: "Grass", type2: "Poison", speciesName: "Seed", height: 0.7, weight: 6.9, ability1: "Overgrow", ability2: "", hiddenAbility: "Chlorophyll", EVYield: "1 Sp. Atk", catchRate: 45, baseFriendship: 70, baseEXP: 64, growthRate: "Medium Slow", eggGroups: ["Grass", "Monster"], maleRate: 87.5, eggCycles: 20, baseStats: [45, 49, 49, 65, 65, 45], evolutions: [Evolution(level: 1, pokemon: "Bulbasaur", method: "", treeLevel: 1), Evolution(level: 16, pokemon: "Ivysaur", method: "Level Up", treeLevel: 2), Evolution(level: 32, pokemon: "Venusaur", method: "Level Up", treeLevel: 3)], dexEntries: [DexEntry(source: "Pokémon Sword", entry: "There is a plant seed on its back right from the day this Pokémon is born. The seed slowly grows larger."), DexEntry(source: "Pokémon Shield", entry: "While it is young, it uses the nutrients that are stored in the seed on its back in order to grow.")], locations: ["Location 1", "Location 2", "Lot3", "Route 4", "Location 5"]),
            Pokemon(name: "Ivysaur", nationalDexNum: "002", type1: "Grass", type2: "Poison", speciesName: "Seed", height: 1.0, weight: 13.0, ability1: "Overgrow", ability2: "", hiddenAbility: "Chlorophyll", EVYield: "1 Sp. Atk, 1 Sp. Def", catchRate: 45, baseFriendship: 70, baseEXP: 142, growthRate: "Medium Slow", eggGroups: ["Grass", "Monster"], maleRate: 87.5, eggCycles: 20, baseStats: [60, 62, 63, 80, 80, 60], evolutions: [Evolution(level: 1, pokemon: "Bulbasaur", method: "", treeLevel: 1), Evolution(level: 16, pokemon: "Ivysaur", method: "Level Up", treeLevel: 2), Evolution(level: 32, pokemon: "Venusaur", method: "Level Up", treeLevel: 3)], dexEntries: [DexEntry(source: "Pokémon Sword", entry: "When the bulb on its back grows large, it appears to lose the ability to stand on its hind legs."), DexEntry(source: "Pokémon Shield", entry: "Exposure to sunlight adds to its strength. Sunlight also makes the bud on its back grow larger.")], locations: []),
            Pokemon(name: "Venusaur", nationalDexNum: "003", type1: "Grass", type2: "Poison", speciesName: "Seed", height: 2.0, weight: 100.0, ability1: "Overgrow", ability2: "", hiddenAbility: "Chlorophyll", EVYield: "2 Sp. Atk, 1 Sp. Def", catchRate: 45, baseFriendship: 70, baseEXP: 236, growthRate: "Medium Slow", eggGroups: ["Grass", "Monster"], maleRate: 87.5, eggCycles: 20, baseStats: [80, 82, 83, 100, 100, 80], evolutions: [Evolution(level: 1, pokemon: "Bulbasaur", method: "", treeLevel: 1), Evolution(level: 16, pokemon: "Ivysaur", method: "Level Up", treeLevel: 2), Evolution(level: 32, pokemon: "Venusaur", method: "Level Up", treeLevel: 3)], dexEntries: [DexEntry(source: "Pokémon Sword", entry: "Its plant blooms when it is absorbing solar energy. It stays on the move to seek sunlight."), DexEntry(source: "Pokémon Shield", entry: "A bewitching aroma wafts from its flower. The fragrance becalms those engaged in a battle.")], locations: []),
            Pokemon(name: "Charmander", nationalDexNum: "004", type1: "Fire", type2: "", speciesName: "Lizard", height: 0.6, weight: 8.5, ability1: "Blaze", ability2: "", hiddenAbility: "Solar Power", EVYield: "1 Speed", catchRate: 45, baseFriendship: 70, baseEXP: 62, growthRate: "Medium Slow", eggGroups: ["Dragon", "Monster"], maleRate: 87.5, eggCycles: 20, baseStats: [39, 52, 43, 60, 50, 65], evolutions: [Evolution(level: 1, pokemon: "Charmander", method: "", treeLevel: 1), Evolution(level: 16, pokemon: "Charmeleon", method: "Level Up", treeLevel: 2), Evolution(level: 36, pokemon: "Charizard", method: "Level Up", treeLevel: 3)], dexEntries: [DexEntry(source: "???", entry: "pp")], locations: [])
        ]
    }
    
    // Functions
    func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(nationalDexNum, forKey: .nationalDexNum)
        try container.encode(type1, forKey: .type1)
        try container.encode(type2, forKey: .type2)
        try container.encode(speciesName, forKey: .speciesName)
        try container.encode(height, forKey: .height)
        try container.encode(weight, forKey: .weight)
        try container.encode(ability1, forKey: .ability1)
        try container.encode(ability2, forKey: .ability2)
        try container.encode(hiddenAbility, forKey: .hiddenAbility)
        try container.encode(EVYield, forKey: .EVYield)
        try container.encode(catchRate, forKey: .catchRate)
        try container.encode(baseFriendship, forKey: .baseFriendship)
        try container.encode(baseEXP, forKey: .baseEXP)
        try container.encode(growthRate, forKey: .growthRate)
        try container.encode(eggGroups, forKey: .eggGroups)
        try container.encode(maleRate, forKey: .maleRate)
        try container.encode(eggCycles, forKey: .eggCycles)
        try container.encode(baseStats, forKey: .baseStats)
        try container.encode(evolutions, forKey: .evolutions)
        try container.encode(dexEntries, forKey: .dexEntries)
        try container.encode(locations, forKey: .locations)
        
    }
    static func findPokemon(name: String) -> Pokemon {
        
        for eachPokemon in pokemonDataList {
            if name == eachPokemon.name {
                return eachPokemon
            }
        }
        return pokemonDataList[0]
        
    }
    
}

extension Pokemon {
    init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: CodingKeys.self)
        name = try values.decode(String.self, forKey: .name)
        nationalDexNum = try values.decode(String.self, forKey: .nationalDexNum)
        type1 = try values.decode(String.self, forKey: .type1)
        type2 = try values.decode(String.self, forKey: .type2)
        speciesName = try values.decode(String.self, forKey: .speciesName)
        height = try values.decode(Double.self, forKey: .height)
        weight = try values.decode(Double.self, forKey: .weight)
        ability1 = try values.decode(String.self, forKey: .ability1)
        ability2 = try values.decode(String.self, forKey: .ability2)
        hiddenAbility = try values.decode(String.self, forKey: .hiddenAbility)
        EVYield = try values.decode(String.self, forKey: .EVYield)
        catchRate = try values.decode(Int.self, forKey: .catchRate)
        baseFriendship = try values.decode(Int.self, forKey: .baseFriendship)
        baseEXP = try values.decode(Int.self, forKey: .baseEXP)
        growthRate = try values.decode(String.self, forKey: .growthRate)
        eggGroups = try values.decode([String].self, forKey: .eggGroups)
        maleRate = try values.decode(Double.self, forKey: .maleRate)
        eggCycles = try values.decode(Int.self, forKey: .eggCycles)
        baseStats = try values.decode([Int].self, forKey: .baseStats)
        evolutions = try values.decode([Evolution].self, forKey: .evolutions)
        dexEntries = try values.decode([DexEntry].self, forKey: .dexEntries)
        locations = try values.decode([String].self, forKey: .locations)
    }
}

struct Evolution: Codable {
    
    // Variables
    var level: Int
    var pokemon: String
    var method: String
    var treeLevel: Int
    
}

struct DexEntry: Codable {
    
    // Variables
    var source: String
    var entry: String
    
}
